# Generated by Django 5.1.5 on 2025-01-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('send_via', models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('Email', 'Email'), ('SMS', 'SMS')], max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
